// app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Chargement des polices locales
const geistSans = localFont({
  src: "./../../public/fonts/GeistVF.woff", // Chemin relatif à partir de public
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./../../public/fonts/GeistMonoVF.woff", // Chemin relatif à partir de public
  variable: "--font-geist-mono",
  weight: "100 900",
});
const novaMono = localFont({
  src: "./../../public/fonts/NovaMono-Regular.ttf", // Chemin relatif à partir de public
  variable: "--font-nova-mono",
  weight: "100 900",
});

// Métadonnées de la page
export const metadata: Metadata = {
  title: "Kylian Gachet",
  description: "Generated by create next app",
};

// Composant de mise en page racine
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${novaMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
